dist/index.js
package-lock.json
package.json
src/index.ts

Add Python versions from tool cache to PATH

---

.github/workflows/test.yml
dist/index.js
src/index.ts

https://github.com/messense/maturin-action/pull/19#discussion_r764517646

Use `docker inspect` to check if docker image exists

---

dist/index.js
src/index.ts

Defaults to manylinux2014 when using `auto` with Rust beta/nightly

---

.github/workflows/test.yml
dist/index.js
src/index.ts

Add support for using manylinux version in `container` option

---

.github/workflows/test.yml
README.md
action.yml
dist/index.js
src/index.ts

Add `working-directory` input option

---

dist/index.js
src/index.ts

Remove hardcoded `MACOSX_DEPLOYMENT_TARGET`

---

dist/index.js
src/index.ts

Forward SSH agent to Docker container

---

dist/index.js
src/index.ts

Add support for `de-vri-es/setup-git-credentials` action

---

src/index.ts

Fix docker image for manylinux_2_28

---

dist/index.js
src/index.ts

Use unshift instead of push to allow passing rustc args

---

.github/workflows/test.yml
dist/index.js
src/index.ts

For now only `s390x` is unsupported

Don't pass `--zig` to unsupported targets

---

.github/workflows/test.yml
dist/index.js
src/index.ts

https://github.com/PyO3/maturin-action/discussions/147

Install `cffi`

---

dist/index.js
src/index.ts

https://github.com/mozilla/sccache/releases/tag/v0.4.0

pip install sccache>=0.4.0

---

dist/index.js
src/index.ts
tests/pyo3-pure/Cargo.lock
tests/pyo3-pure/Cargo.toml

Write `run-maturin-action.sh` to a tmpdir

---

.github/workflows/test.yml

It's much faster than macOS 12 (macos-latest at the moment).

Run tests on macOS 13 runner

---

dist/index.js
src/index.ts

Also find `rust-toolchain` file in parent directories

---

dist/index.js
src/index.ts

Allow absolute `working-directory`

---

dist/index.js
src/index.ts

Add support for `--target=`

---

dist/index.js
src/index.ts

Closes: https://github.com/PyO3/maturin-action/issues/321

Add GITHUB_ to ALLOWED_ENV_PREFIXES

---

.github/workflows/test.yml
dist/index.js
src/index.ts

Workaround https://github.com/rust-lang/cargo/issues/13546

Install libatomic for cargo on i686 Linux targets

---

dist/index.js
src/index.ts

The rustup installation already fails without libatomic, so libatomic must be installed first. Not sure how tests passed

Fix i686 libatomic install

---

.github/workflows/test.yml
README.md
dist/index.js
src/index.ts

Use Docker image added in https://github.com/rust-cross/manylinux-cross/pull/101

Add manylinux_2_31 riscv64gc-unknown-linux-gnu

---

.github/workflows/test.yml
README.md
dist/index.js
src/index.ts

- https://github.com/pypa/auditwheel/pull/522
- https://github.com/rust-cross/manylinux-cross/pull/102
- https://github.com/rust-cross/manylinux-cross/pull/103

Add manylinux_2_36 loongarch64-unknown-linux-gnu

---

src/index.ts

Add recent manylinux images for i686

---

.github/workflows/update.yml

I think this should fix the broken workflow. (Probably caused by #373)
cc @messense, I'm going to merge and rerun the update action. Please forgive 🙏

Add write permissions for contents
